import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLanguage {
  final String code;
  final String name;
  final String storyInstruction;

  const AppLanguage({required this.code, required this.name, required this.storyInstruction});
}

const List<AppLanguage> supportedLanguages = [
  AppLanguage(code: 'en', name: "English", storyInstruction: "English"),
  AppLanguage(code: 'fil', name: "Filipino / Tagalog", storyInstruction: "Filipino or Tagalog"),
  AppLanguage(code: 'ko', name: "Korean", storyInstruction: "Korean"),
  AppLanguage(code: 'ja', name: "Japanese", storyInstruction: "Japanese"),
  AppLanguage(code: 'zh', name: "Mandarin Chinese", storyInstruction: "Mandarin Chinese using Simplified Chinese characters"),
  AppLanguage(code: 'nl', name: "Dutch", storyInstruction: "Dutch"),
  AppLanguage(code: 'es', name: "Spanish", storyInstruction: "Spanish"),
];

class LanguageController {
  static final ValueNotifier<AppLanguage> current = ValueNotifier<AppLanguage>(supportedLanguages.first);

  static Future<void> load() async {
    current.value = await LanguageService().getPreferredLanguage();
  }

  static Future<void> setLanguageCode(String code, {bool save = true}) async {
    final language = languageByCode(code);
    current.value = language;
    if (save) await LanguageService().savePreferredLanguageCode(language.code);
  }
}

class LanguageService {
  static const String _globalLanguageKey = 'heritagebot_preferred_language';
  static const String _userLanguagePrefix = 'heritagebot_user_language_';

  String? get _currentUid => FirebaseAuth.instance.currentUser?.uid;
  String _userKey(String uid) => '$_userLanguagePrefix$uid';

  Future<void> savePreferredLanguageCode(String code) async {
    final prefs = await SharedPreferences.getInstance();
    final safeCode = languageByCode(code).code;
    await prefs.remove(_globalLanguageKey);
    await prefs.setString(_globalLanguageKey, safeCode);
    final uid = _currentUid;
    if (uid != null && uid.trim().isNotEmpty) {
      await prefs.remove(_userKey(uid));
      await prefs.setString(_userKey(uid), safeCode);
    }
  }

  Future<String> getPreferredLanguageCode() async {
    final prefs = await SharedPreferences.getInstance();
    final uid = _currentUid;
    if (uid != null && uid.trim().isNotEmpty) {
      final userCode = await _normalizeSavedValue(prefs.get(_userKey(uid)), prefs, _userKey(uid));
      if (userCode != null) return userCode;
    }
    final globalCode = await _normalizeSavedValue(prefs.get(_globalLanguageKey), prefs, _globalLanguageKey);
    if (globalCode != null) return globalCode;
    await savePreferredLanguageCode('en');
    return 'en';
  }

  Future<String?> _normalizeSavedValue(dynamic savedValue, SharedPreferences prefs, String key) async {
    if (savedValue is String && savedValue.trim().isNotEmpty) {
      final safeCode = languageByCode(savedValue.trim()).code;
      await prefs.setString(key, safeCode);
      return safeCode;
    }
    if (savedValue is List<String> && savedValue.isNotEmpty) {
      final safeCode = languageByCode(savedValue.first.trim()).code;
      await prefs.remove(key);
      await prefs.setString(key, safeCode);
      return safeCode;
    }
    if (savedValue != null) await prefs.remove(key);
    return null;
  }

  Future<AppLanguage> getPreferredLanguage() async => languageByCode(await getPreferredLanguageCode());
}

AppLanguage languageByCode(String code) {
  return supportedLanguages.firstWhere((language) => language.code == code, orElse: () => supportedLanguages.first);
}

String appText(String code, String key) {
  final normalizedCode = languageByCode(code).code;
  return _localizedText[normalizedCode]?[key] ?? _localizedText['en']?[key] ?? key;
}

const Map<String, Map<String, String>> _localizedText = {
  "en": {
    "appSubtitle": "AI-Based Historical Narrative\nand Memory Companion",
    "createAccount": "Create Account",
    "welcomeBack": "Welcome Back",
    "signupPrompt": "Sign up and choose your preferred language.",
    "loginPrompt": "Login to continue your heritage journey.",
    "emailAddress": "Email address",
    "password": "Password",
    "confirmPassword": "Confirm password",
    "preferredLanguage": "Preferred Language",
    "forgotPassword": "Forgot Password?",
    "pleaseWait": "Please wait...",
    "createAndSendLink": "Create Account",
    "login": "Login",
    "orContinueWith": "or continue with",
    "continueWithGmail": "Continue with Gmail",
    "continueWithFacebook": "Continue with Facebook",
    "alreadyHaveAccount": "Already have an account? Login",
    "noAccount": "No account yet? Sign up",
    "enterEmailPassword": "Please enter email and password.",
    "passwordLength": "Password must be at least 6 characters.",
    "confirmYourPassword": "Please confirm your password.",
    "passwordsDoNotMatch": "Passwords do not match.",
    "enterEmailFirst": "Please enter your email address first.",
    "validEmail": "Please enter a valid email address.",
    "resetSent": "Password reset link sent. Please check your Gmail.",
    "noAccountFound": "No account found with this email.",
    "invalidEmail": "Invalid email address.",
    "resetFailed": "Failed to send password reset link. Please try again.",
    "authError": "Authentication error.",
    "home": "Home",
    "geolocation": "Geolocation",
    "myJournal": "My Journal",
    "profile": "Profile",
    "welcomeHome": "Welcome to\nHeritageBot",
    "homeIntro": "HeritageBot is a location-aware mobile application that generates AI-based historical stories, shows live map movement, and saves personal memory journals.",
    "aboutSystem": "About the System",
    "aboutSystemBody": "The system uses geolocation and Gemini API to generate context-aware heritage stories based on the user’s nearby location.",
    "aiStoryTitle": "AI-Generated Heritage Story",
    "aiStoryBody": "The context-aware story is generated using Gemini API when the system detects a nearby place. It is not stored as fixed text.",
    "liveMapTitle": "Live Movement Map",
    "liveMapBody": "The map follows your current GPS location while walking or driving, showing movement in real time.",
    "memoryJournalTitle": "Memory Journal",
    "memoryJournalBody": "Users can save private personal memories, photos, and videos connected to heritage places.",
    "heritageVideos": "Heritage Videos",
    "liveGeolocation": "Live Geolocation",
    "failedLocation": "Failed to get location",
    "startingLocation": "Starting live location tracking...",
    "mapReady": "Live movement map is ready.",
    "mapInstruction": "The blue navigation marker follows your phone GPS while walking or driving. The story is generated by Gemini API when a nearby place is detected.",
    "refreshLocation": "Regenerate / Refresh Location",
    "nearest": "Nearest",
    "kmAway": "km away",
    "generatingStory": "Generating AI Heritage Story",
    "generatingStoryBody": "HeritageBot is generating a context-aware story using Gemini API...",
    "contextStoryTitle": "AI Context-Aware Heritage Story",
    "generatingImage": "Generating AI Heritage Image",
    "generatingImageBody": "HeritageBot is creating an AI image based on your nearby location and generated story...",
    "aiImageTitle": "AI Location-Based Heritage Image",
    "aiImageFallbackTitle": "Heritage Image Preview",
    "aiImageFallbackBody": "The live AI image service is unavailable, so HeritageBot is showing a local illustrative heritage preview for this place.",
    "noVideo": "No Video Available",
    "noVideoBody": "This nearest place has no assigned video yet.",
    "addMemoryHere": "Add Personal Memory Here",
    "noSavedMemories": "No saved memories for this place yet.",
    "previousMemories": "Your Previous Memories Here",
    "chooseHeritagePlace": "Choose Heritage Place",
    "chooseHeritagePlaceBody": "Select where this journal memory belongs.",
    "noJournal": "No journal yet. Tap + to add a letter, photos, or videos connected to a heritage place.",
    "addMemory": "Add Memory",
    "addMemorySubtitle": "Write a letter or add family photos/videos connected to this place.",
    "writeMemoryLetter": "Write your memory letter",
    "selectedPictures": "Selected Pictures",
    "selectedVideos": "Selected Videos",
    "saveMemory": "Save Memory",
    "saving": "Saving...",
    "journalSaved": "Journal memory saved.",
    "profileUser": "HeritageBot User",
    "noEmail": "No email available",
    "changePassword": "Change Password",
    "changePasswordUnavailable": "Change Password Unavailable",
    "changePasswordUnavailableMsg": "Change password is only available for email/password accounts.",
    "logout": "Logout",
    "systemNote": "System Note",
    "systemNoteBody": "This profile is connected to Firebase Authentication. Email, Gmail, and Facebook users will appear in Firebase Authentication → Users.",
    "languageSettings": "Language Settings",
    "languageSaved": "Language preference saved.",
    "attachedVideo": "Attached video"
  },
  "zh": {
    "appSubtitle": "基于 AI 的历史叙事\n与记忆助手",
    "createAccount": "创建账户",
    "welcomeBack": "欢迎回来",
    "signupPrompt": "注册并选择你的首选语言。",
    "loginPrompt": "登录以继续你的文化遗产之旅。",
    "emailAddress": "电子邮件地址",
    "password": "密码",
    "confirmPassword": "确认密码",
    "preferredLanguage": "首选语言",
    "forgotPassword": "忘记密码？",
    "pleaseWait": "请稍候...",
    "createAndSendLink": "创建账户",
    "login": "登录",
    "orContinueWith": "或使用以下方式继续",
    "continueWithGmail": "使用 Gmail 继续",
    "continueWithFacebook": "使用 Facebook 继续",
    "alreadyHaveAccount": "已有账户？登录",
    "noAccount": "还没有账户？注册",
    "enterEmailPassword": "请输入电子邮件和密码。",
    "passwordLength": "密码至少需要 6 个字符。",
    "confirmYourPassword": "请确认你的密码。",
    "passwordsDoNotMatch": "两次输入的密码不一致。",
    "enterEmailFirst": "请先输入你的电子邮件地址。",
    "validEmail": "请输入有效的电子邮件地址。",
    "resetSent": "密码重置链接已发送。请检查你的 Gmail。",
    "noAccountFound": "没有找到使用此电子邮件的账户。",
    "invalidEmail": "电子邮件地址无效。",
    "resetFailed": "发送密码重置链接失败。请再试一次。",
    "authError": "认证错误。",
    "home": "首页",
    "geolocation": "定位",
    "myJournal": "我的日志",
    "profile": "个人资料",
    "welcomeHome": "欢迎使用\nHeritageBot",
    "homeIntro": "HeritageBot 是一款基于位置的移动应用，可生成 AI 历史故事、显示实时地图移动并保存个人记忆日志。",
    "aboutSystem": "关于系统",
    "aboutSystemBody": "该系统使用地理定位和 Gemini API，根据用户附近的位置生成情境化文化遗产故事。",
    "aiStoryTitle": "AI 生成的文化遗产故事",
    "aiStoryBody": "当系统检测到附近地点时，会使用 Gemini API 生成情境化故事。它不是固定文本。",
    "liveMapTitle": "实时移动地图",
    "liveMapBody": "地图会在用户步行或驾驶时实时跟随当前 GPS 位置。",
    "memoryJournalTitle": "记忆日志",
    "memoryJournalBody": "用户可以私密保存与文化遗产地点相关的个人记忆、照片和视频。",
    "heritageVideos": "文化遗产视频",
    "liveGeolocation": "实时定位",
    "failedLocation": "获取位置失败",
    "startingLocation": "正在启动实时位置跟踪...",
    "mapReady": "实时移动地图已准备好。",
    "mapInstruction": "蓝色导航标记会跟随手机 GPS。当检测到附近地点时，Gemini API 会生成故事。",
    "refreshLocation": "重新生成 / 刷新位置",
    "nearest": "最近",
    "kmAway": "公里外",
    "generatingStory": "正在生成 AI 文化遗产故事",
    "generatingStoryBody": "HeritageBot 正在使用 Gemini API 生成情境化故事...",
    "contextStoryTitle": "AI 情境化文化遗产故事",
    "generatingImage": "正在生成 AI 文化遗产图像",
    "generatingImageBody": "HeritageBot 正在根据你附近的位置和故事创建 AI 图像...",
    "aiImageTitle": "AI 位置文化遗产图像",
    "aiImageFallbackTitle": "文化遗产图像预览",
    "aiImageFallbackBody": "实时 AI 图像服务暂不可用，因此 HeritageBot 正在显示本地文化遗产预览图。",
    "noVideo": "无视频",
    "noVideoBody": "这个地点还没有指定视频。",
    "addMemoryHere": "在这里添加个人记忆",
    "noSavedMemories": "这个地点还没有保存的记忆。",
    "previousMemories": "你以前的记忆",
    "chooseHeritagePlace": "选择文化遗产地点",
    "chooseHeritagePlaceBody": "选择此日志记忆所属的地点。",
    "noJournal": "还没有日志。点击 + 添加与文化遗产地点相关的信件、照片或视频。",
    "addMemory": "添加记忆",
    "addMemorySubtitle": "写一封信或添加与此地点相关的家庭照片/视频。",
    "writeMemoryLetter": "写下你的记忆信件",
    "selectedPictures": "已选图片",
    "selectedVideos": "已选视频",
    "saveMemory": "保存记忆",
    "saving": "正在保存...",
    "journalSaved": "日志记忆已保存。",
    "profileUser": "HeritageBot 用户",
    "noEmail": "没有可用电子邮件",
    "changePassword": "更改密码",
    "changePasswordUnavailable": "无法更改密码",
    "changePasswordUnavailableMsg": "更改密码仅适用于电子邮件/密码账户。",
    "logout": "退出登录",
    "systemNote": "系统说明",
    "systemNoteBody": "此个人资料已连接到 Firebase Authentication。",
    "languageSettings": "语言设置",
    "languageSaved": "语言偏好已保存。",
    "attachedVideo": "附加视频"
  },
  "ja": {
    "appSubtitle": "AIベースの歴史ナラティブ\nおよびメモリーコンパニオン",
    "createAccount": "アカウント作成",
    "welcomeBack": "おかえりなさい",
    "signupPrompt": "登録して希望する言語を選択してください。",
    "loginPrompt": "文化遺産の旅を続けるにはログインしてください。",
    "emailAddress": "メールアドレス",
    "password": "パスワード",
    "confirmPassword": "パスワード確認",
    "preferredLanguage": "希望言語",
    "forgotPassword": "パスワードをお忘れですか？",
    "pleaseWait": "お待ちください...",
    "createAndSendLink": "アカウント作成",
    "login": "ログイン",
    "orContinueWith": "または次で続行",
    "continueWithGmail": "Gmailで続行",
    "continueWithFacebook": "Facebookで続行",
    "alreadyHaveAccount": "すでにアカウントがありますか？ログイン",
    "noAccount": "アカウントがありませんか？登録",
    "enterEmailPassword": "メールアドレスとパスワードを入力してください。",
    "passwordLength": "パスワードは6文字以上である必要があります。",
    "confirmYourPassword": "パスワードを確認してください。",
    "passwordsDoNotMatch": "パスワードが一致しません。",
    "enterEmailFirst": "先にメールアドレスを入力してください。",
    "validEmail": "有効なメールアドレスを入力してください。",
    "resetSent": "パスワード再設定リンクを送信しました。Gmailを確認してください。",
    "noAccountFound": "このメールのアカウントは見つかりません。",
    "invalidEmail": "無効なメールアドレスです。",
    "resetFailed": "パスワード再設定リンクを送信できませんでした。もう一度お試しください。",
    "authError": "認証エラーが発生しました。",
    "home": "ホーム",
    "geolocation": "位置情報",
    "myJournal": "マイジャーナル",
    "profile": "プロフィール",
    "welcomeHome": "HeritageBotへ\nようこそ",
    "homeIntro": "HeritageBotは位置情報に対応したモバイルアプリで、AIによる歴史ストーリー、リアルタイム地図、個人の思い出ジャーナルを提供します。",
    "aboutSystem": "システムについて",
    "aboutSystemBody": "このシステムは位置情報とGemini APIを使用して、ユーザーの近くの場所に基づいた文化遺産ストーリーを生成します。",
    "aiStoryTitle": "AI生成文化遺産ストーリー",
    "aiStoryBody": "近くの場所を検出すると、Gemini APIを使用して状況に応じたストーリーが生成されます。",
    "liveMapTitle": "ライブ移動マップ",
    "liveMapBody": "地図は歩行中または運転中の現在のGPS位置をリアルタイムで追跡します。",
    "memoryJournalTitle": "メモリージャーナル",
    "memoryJournalBody": "ユーザーは文化遺産の場所に関連する個人的な思い出、写真、動画を非公開で保存できます。",
    "heritageVideos": "文化遺産動画",
    "liveGeolocation": "ライブ位置情報",
    "failedLocation": "位置情報の取得に失敗しました",
    "startingLocation": "ライブ位置追跡を開始しています...",
    "mapReady": "ライブ移動マップの準備ができました。",
    "mapInstruction": "青いマーカーはスマートフォンのGPSに従います。近くの場所が検出されるとGemini APIがストーリーを生成します。",
    "refreshLocation": "位置を更新",
    "nearest": "最寄り",
    "kmAway": "km 離れています",
    "generatingStory": "AI文化遺産ストーリー生成中",
    "generatingStoryBody": "HeritageBotがGemini APIを使用してストーリーを生成しています...",
    "contextStoryTitle": "AI状況対応文化遺産ストーリー",
    "generatingImage": "AI文化遺産画像を生成中",
    "generatingImageBody": "HeritageBotが現在地とストーリーに基づいてAI画像を生成しています...",
    "aiImageTitle": "AI位置ベース文化遺産画像",
    "aiImageFallbackTitle": "文化遺産画像プレビュー",
    "aiImageFallbackBody": "ライブAI画像サービスが利用できないため、ローカルの文化遺産プレビューを表示しています。",
    "noVideo": "動画なし",
    "noVideoBody": "この場所にはまだ動画が割り当てられていません。",
    "addMemoryHere": "ここに個人の思い出を追加",
    "noSavedMemories": "この場所には保存された思い出がありません。",
    "previousMemories": "以前の思い出",
    "chooseHeritagePlace": "文化遺産の場所を選択",
    "chooseHeritagePlaceBody": "このジャーナルの思い出が属する場所を選択してください。",
    "noJournal": "まだジャーナルはありません。+ をタップして手紙、写真、動画を追加してください。",
    "addMemory": "思い出を追加",
    "addMemorySubtitle": "この場所に関連する手紙を書いたり、写真/動画を追加したりできます。",
    "writeMemoryLetter": "思い出の手紙を書く",
    "selectedPictures": "選択した写真",
    "selectedVideos": "選択した動画",
    "saveMemory": "思い出を保存",
    "saving": "保存中...",
    "journalSaved": "ジャーナルの思い出を保存しました。",
    "profileUser": "HeritageBotユーザー",
    "noEmail": "メールなし",
    "changePassword": "パスワード変更",
    "changePasswordUnavailable": "パスワード変更不可",
    "changePasswordUnavailableMsg": "パスワード変更はメール/パスワードアカウントのみ利用できます。",
    "logout": "ログアウト",
    "systemNote": "システムメモ",
    "systemNoteBody": "このプロフィールはFirebase Authenticationに接続されています。",
    "languageSettings": "言語設定",
    "languageSaved": "言語設定を保存しました。",
    "attachedVideo": "添付動画"
  },
  "fil": {
    "appSubtitle": "AI-Based Historical Narrative\nand Memory Companion",
    "createAccount": "Gumawa ng Account",
    "welcomeBack": "Maligayang Pagbalik",
    "signupPrompt": "Sign up and choose your preferred language.",
    "loginPrompt": "Login to continue your heritage journey.",
    "emailAddress": "Email address",
    "password": "Password",
    "confirmPassword": "Confirm password",
    "preferredLanguage": "Piniling Wika",
    "forgotPassword": "Forgot Password?",
    "pleaseWait": "Please wait...",
    "createAndSendLink": "Create Account",
    "login": "Login",
    "orContinueWith": "or continue with",
    "continueWithGmail": "Continue with Gmail",
    "continueWithFacebook": "Continue with Facebook",
    "alreadyHaveAccount": "Already have an account? Login",
    "noAccount": "No account yet? Sign up",
    "enterEmailPassword": "Please enter email and password.",
    "passwordLength": "Password must be at least 6 characters.",
    "confirmYourPassword": "Please confirm your password.",
    "passwordsDoNotMatch": "Passwords do not match.",
    "enterEmailFirst": "Please enter your email address first.",
    "validEmail": "Please enter a valid email address.",
    "resetSent": "Password reset link sent. Please check your Gmail.",
    "noAccountFound": "No account found with this email.",
    "invalidEmail": "Invalid email address.",
    "resetFailed": "Failed to send password reset link. Please try again.",
    "authError": "Authentication error.",
    "home": "Home",
    "geolocation": "Geolocation",
    "myJournal": "Aking Journal",
    "profile": "Profile",
    "welcomeHome": "Welcome to\nHeritageBot",
    "homeIntro": "HeritageBot is a location-aware mobile application that generates AI-based historical stories, shows live map movement, and saves personal memory journals.",
    "aboutSystem": "About the System",
    "aboutSystemBody": "The system uses geolocation and Gemini API to generate context-aware heritage stories based on the user’s nearby location.",
    "aiStoryTitle": "AI-Generated Heritage Story",
    "aiStoryBody": "The context-aware story is generated using Gemini API when the system detects a nearby place. It is not stored as fixed text.",
    "liveMapTitle": "Live Movement Map",
    "liveMapBody": "The map follows your current GPS location while walking or driving, showing movement in real time.",
    "memoryJournalTitle": "Memory Journal",
    "memoryJournalBody": "Users can save private personal memories, photos, and videos connected to heritage places.",
    "heritageVideos": "Heritage Videos",
    "liveGeolocation": "Live Geolocation",
    "failedLocation": "Failed to get location",
    "startingLocation": "Starting live location tracking...",
    "mapReady": "Live movement map is ready.",
    "mapInstruction": "The blue navigation marker follows your phone GPS while walking or driving. The story is generated by Gemini API when a nearby place is detected.",
    "refreshLocation": "Regenerate / Refresh Location",
    "nearest": "Nearest",
    "kmAway": "km away",
    "generatingStory": "Generating AI Heritage Story",
    "generatingStoryBody": "HeritageBot is generating a context-aware story using Gemini API...",
    "contextStoryTitle": "AI Context-Aware Heritage Story",
    "generatingImage": "Generating AI Heritage Image",
    "generatingImageBody": "HeritageBot is creating an AI image based on your nearby location and generated story...",
    "aiImageTitle": "AI Location-Based Heritage Image",
    "aiImageFallbackTitle": "Heritage Image Preview",
    "aiImageFallbackBody": "The live AI image service is unavailable, so HeritageBot is showing a local illustrative heritage preview for this place.",
    "noVideo": "No Video Available",
    "noVideoBody": "This nearest place has no assigned video yet.",
    "addMemoryHere": "Add Personal Memory Here",
    "noSavedMemories": "No saved memories for this place yet.",
    "previousMemories": "Your Previous Memories Here",
    "chooseHeritagePlace": "Choose Heritage Place",
    "chooseHeritagePlaceBody": "Select where this journal memory belongs.",
    "noJournal": "No journal yet. Tap + to add a letter, photos, or videos connected to a heritage place.",
    "addMemory": "Add Memory",
    "addMemorySubtitle": "Write a letter or add family photos/videos connected to this place.",
    "writeMemoryLetter": "Write your memory letter",
    "selectedPictures": "Selected Pictures",
    "selectedVideos": "Selected Videos",
    "saveMemory": "Save Memory",
    "saving": "Saving...",
    "journalSaved": "Journal memory saved.",
    "profileUser": "HeritageBot User",
    "noEmail": "No email available",
    "changePassword": "Palitan ang Password",
    "changePasswordUnavailable": "Change Password Unavailable",
    "changePasswordUnavailableMsg": "Change password is only available for email/password accounts.",
    "logout": "Logout",
    "systemNote": "System Note",
    "systemNoteBody": "This profile is connected to Firebase Authentication. Email, Gmail, and Facebook users will appear in Firebase Authentication → Users.",
    "languageSettings": "Language Settings",
    "languageSaved": "Na-save ang language preference.",
    "attachedVideo": "Attached video"
  },
  "ko": {
    "appSubtitle": "AI-Based Historical Narrative\nand Memory Companion",
    "createAccount": "계정 만들기",
    "welcomeBack": "다시 오신 것을 환영합니다",
    "signupPrompt": "Sign up and choose your preferred language.",
    "loginPrompt": "Login to continue your heritage journey.",
    "emailAddress": "Email address",
    "password": "Password",
    "confirmPassword": "Confirm password",
    "preferredLanguage": "선호 언어",
    "forgotPassword": "Forgot Password?",
    "pleaseWait": "Please wait...",
    "createAndSendLink": "Create Account",
    "login": "Login",
    "orContinueWith": "or continue with",
    "continueWithGmail": "Continue with Gmail",
    "continueWithFacebook": "Continue with Facebook",
    "alreadyHaveAccount": "Already have an account? Login",
    "noAccount": "No account yet? Sign up",
    "enterEmailPassword": "Please enter email and password.",
    "passwordLength": "Password must be at least 6 characters.",
    "confirmYourPassword": "Please confirm your password.",
    "passwordsDoNotMatch": "Passwords do not match.",
    "enterEmailFirst": "Please enter your email address first.",
    "validEmail": "Please enter a valid email address.",
    "resetSent": "Password reset link sent. Please check your Gmail.",
    "noAccountFound": "No account found with this email.",
    "invalidEmail": "Invalid email address.",
    "resetFailed": "Failed to send password reset link. Please try again.",
    "authError": "Authentication error.",
    "home": "홈",
    "geolocation": "위치",
    "myJournal": "내 저널",
    "profile": "프로필",
    "welcomeHome": "Welcome to\nHeritageBot",
    "homeIntro": "HeritageBot is a location-aware mobile application that generates AI-based historical stories, shows live map movement, and saves personal memory journals.",
    "aboutSystem": "About the System",
    "aboutSystemBody": "The system uses geolocation and Gemini API to generate context-aware heritage stories based on the user’s nearby location.",
    "aiStoryTitle": "AI-Generated Heritage Story",
    "aiStoryBody": "The context-aware story is generated using Gemini API when the system detects a nearby place. It is not stored as fixed text.",
    "liveMapTitle": "Live Movement Map",
    "liveMapBody": "The map follows your current GPS location while walking or driving, showing movement in real time.",
    "memoryJournalTitle": "Memory Journal",
    "memoryJournalBody": "Users can save private personal memories, photos, and videos connected to heritage places.",
    "heritageVideos": "Heritage Videos",
    "liveGeolocation": "실시간 위치",
    "failedLocation": "Failed to get location",
    "startingLocation": "Starting live location tracking...",
    "mapReady": "Live movement map is ready.",
    "mapInstruction": "The blue navigation marker follows your phone GPS while walking or driving. The story is generated by Gemini API when a nearby place is detected.",
    "refreshLocation": "Regenerate / Refresh Location",
    "nearest": "Nearest",
    "kmAway": "km away",
    "generatingStory": "Generating AI Heritage Story",
    "generatingStoryBody": "HeritageBot is generating a context-aware story using Gemini API...",
    "contextStoryTitle": "AI Context-Aware Heritage Story",
    "generatingImage": "Generating AI Heritage Image",
    "generatingImageBody": "HeritageBot is creating an AI image based on your nearby location and generated story...",
    "aiImageTitle": "AI Location-Based Heritage Image",
    "aiImageFallbackTitle": "Heritage Image Preview",
    "aiImageFallbackBody": "The live AI image service is unavailable, so HeritageBot is showing a local illustrative heritage preview for this place.",
    "noVideo": "No Video Available",
    "noVideoBody": "This nearest place has no assigned video yet.",
    "addMemoryHere": "Add Personal Memory Here",
    "noSavedMemories": "No saved memories for this place yet.",
    "previousMemories": "Your Previous Memories Here",
    "chooseHeritagePlace": "Choose Heritage Place",
    "chooseHeritagePlaceBody": "Select where this journal memory belongs.",
    "noJournal": "No journal yet. Tap + to add a letter, photos, or videos connected to a heritage place.",
    "addMemory": "Add Memory",
    "addMemorySubtitle": "Write a letter or add family photos/videos connected to this place.",
    "writeMemoryLetter": "Write your memory letter",
    "selectedPictures": "Selected Pictures",
    "selectedVideos": "Selected Videos",
    "saveMemory": "Save Memory",
    "saving": "Saving...",
    "journalSaved": "Journal memory saved.",
    "profileUser": "HeritageBot User",
    "noEmail": "No email available",
    "changePassword": "비밀번호 변경",
    "changePasswordUnavailable": "Change Password Unavailable",
    "changePasswordUnavailableMsg": "Change password is only available for email/password accounts.",
    "logout": "로그아웃",
    "systemNote": "System Note",
    "systemNoteBody": "This profile is connected to Firebase Authentication. Email, Gmail, and Facebook users will appear in Firebase Authentication → Users.",
    "languageSettings": "언어 설정",
    "languageSaved": "언어 설정이 저장되었습니다.",
    "attachedVideo": "Attached video"
  },
  "nl": {
    "appSubtitle": "AI-Based Historical Narrative\nand Memory Companion",
    "createAccount": "Account maken",
    "welcomeBack": "Welkom terug",
    "signupPrompt": "Sign up and choose your preferred language.",
    "loginPrompt": "Login to continue your heritage journey.",
    "emailAddress": "Email address",
    "password": "Password",
    "confirmPassword": "Confirm password",
    "preferredLanguage": "Voorkeurstaal",
    "forgotPassword": "Forgot Password?",
    "pleaseWait": "Please wait...",
    "createAndSendLink": "Create Account",
    "login": "Login",
    "orContinueWith": "or continue with",
    "continueWithGmail": "Continue with Gmail",
    "continueWithFacebook": "Continue with Facebook",
    "alreadyHaveAccount": "Already have an account? Login",
    "noAccount": "No account yet? Sign up",
    "enterEmailPassword": "Please enter email and password.",
    "passwordLength": "Password must be at least 6 characters.",
    "confirmYourPassword": "Please confirm your password.",
    "passwordsDoNotMatch": "Passwords do not match.",
    "enterEmailFirst": "Please enter your email address first.",
    "validEmail": "Please enter a valid email address.",
    "resetSent": "Password reset link sent. Please check your Gmail.",
    "noAccountFound": "No account found with this email.",
    "invalidEmail": "Invalid email address.",
    "resetFailed": "Failed to send password reset link. Please try again.",
    "authError": "Authentication error.",
    "home": "Home",
    "geolocation": "Locatie",
    "myJournal": "Mijn dagboek",
    "profile": "Profiel",
    "welcomeHome": "Welcome to\nHeritageBot",
    "homeIntro": "HeritageBot is a location-aware mobile application that generates AI-based historical stories, shows live map movement, and saves personal memory journals.",
    "aboutSystem": "About the System",
    "aboutSystemBody": "The system uses geolocation and Gemini API to generate context-aware heritage stories based on the user’s nearby location.",
    "aiStoryTitle": "AI-Generated Heritage Story",
    "aiStoryBody": "The context-aware story is generated using Gemini API when the system detects a nearby place. It is not stored as fixed text.",
    "liveMapTitle": "Live Movement Map",
    "liveMapBody": "The map follows your current GPS location while walking or driving, showing movement in real time.",
    "memoryJournalTitle": "Memory Journal",
    "memoryJournalBody": "Users can save private personal memories, photos, and videos connected to heritage places.",
    "heritageVideos": "Heritage Videos",
    "liveGeolocation": "Live locatie",
    "failedLocation": "Failed to get location",
    "startingLocation": "Starting live location tracking...",
    "mapReady": "Live movement map is ready.",
    "mapInstruction": "The blue navigation marker follows your phone GPS while walking or driving. The story is generated by Gemini API when a nearby place is detected.",
    "refreshLocation": "Regenerate / Refresh Location",
    "nearest": "Nearest",
    "kmAway": "km away",
    "generatingStory": "Generating AI Heritage Story",
    "generatingStoryBody": "HeritageBot is generating a context-aware story using Gemini API...",
    "contextStoryTitle": "AI Context-Aware Heritage Story",
    "generatingImage": "Generating AI Heritage Image",
    "generatingImageBody": "HeritageBot is creating an AI image based on your nearby location and generated story...",
    "aiImageTitle": "AI Location-Based Heritage Image",
    "aiImageFallbackTitle": "Heritage Image Preview",
    "aiImageFallbackBody": "The live AI image service is unavailable, so HeritageBot is showing a local illustrative heritage preview for this place.",
    "noVideo": "No Video Available",
    "noVideoBody": "This nearest place has no assigned video yet.",
    "addMemoryHere": "Add Personal Memory Here",
    "noSavedMemories": "No saved memories for this place yet.",
    "previousMemories": "Your Previous Memories Here",
    "chooseHeritagePlace": "Choose Heritage Place",
    "chooseHeritagePlaceBody": "Select where this journal memory belongs.",
    "noJournal": "No journal yet. Tap + to add a letter, photos, or videos connected to a heritage place.",
    "addMemory": "Add Memory",
    "addMemorySubtitle": "Write a letter or add family photos/videos connected to this place.",
    "writeMemoryLetter": "Write your memory letter",
    "selectedPictures": "Selected Pictures",
    "selectedVideos": "Selected Videos",
    "saveMemory": "Save Memory",
    "saving": "Saving...",
    "journalSaved": "Journal memory saved.",
    "profileUser": "HeritageBot User",
    "noEmail": "No email available",
    "changePassword": "Wachtwoord wijzigen",
    "changePasswordUnavailable": "Change Password Unavailable",
    "changePasswordUnavailableMsg": "Change password is only available for email/password accounts.",
    "logout": "Uitloggen",
    "systemNote": "System Note",
    "systemNoteBody": "This profile is connected to Firebase Authentication. Email, Gmail, and Facebook users will appear in Firebase Authentication → Users.",
    "languageSettings": "Taalinstellingen",
    "languageSaved": "Taalvoorkeur opgeslagen.",
    "attachedVideo": "Attached video"
  },
  "es": {
    "appSubtitle": "AI-Based Historical Narrative\nand Memory Companion",
    "createAccount": "Crear cuenta",
    "welcomeBack": "Bienvenido de nuevo",
    "signupPrompt": "Sign up and choose your preferred language.",
    "loginPrompt": "Login to continue your heritage journey.",
    "emailAddress": "Email address",
    "password": "Password",
    "confirmPassword": "Confirm password",
    "preferredLanguage": "Idioma preferido",
    "forgotPassword": "Forgot Password?",
    "pleaseWait": "Please wait...",
    "createAndSendLink": "Create Account",
    "login": "Login",
    "orContinueWith": "or continue with",
    "continueWithGmail": "Continue with Gmail",
    "continueWithFacebook": "Continue with Facebook",
    "alreadyHaveAccount": "Already have an account? Login",
    "noAccount": "No account yet? Sign up",
    "enterEmailPassword": "Please enter email and password.",
    "passwordLength": "Password must be at least 6 characters.",
    "confirmYourPassword": "Please confirm your password.",
    "passwordsDoNotMatch": "Passwords do not match.",
    "enterEmailFirst": "Please enter your email address first.",
    "validEmail": "Please enter a valid email address.",
    "resetSent": "Password reset link sent. Please check your Gmail.",
    "noAccountFound": "No account found with this email.",
    "invalidEmail": "Invalid email address.",
    "resetFailed": "Failed to send password reset link. Please try again.",
    "authError": "Authentication error.",
    "home": "Inicio",
    "geolocation": "Ubicación",
    "myJournal": "Mi diario",
    "profile": "Perfil",
    "welcomeHome": "Welcome to\nHeritageBot",
    "homeIntro": "HeritageBot is a location-aware mobile application that generates AI-based historical stories, shows live map movement, and saves personal memory journals.",
    "aboutSystem": "About the System",
    "aboutSystemBody": "The system uses geolocation and Gemini API to generate context-aware heritage stories based on the user’s nearby location.",
    "aiStoryTitle": "AI-Generated Heritage Story",
    "aiStoryBody": "The context-aware story is generated using Gemini API when the system detects a nearby place. It is not stored as fixed text.",
    "liveMapTitle": "Live Movement Map",
    "liveMapBody": "The map follows your current GPS location while walking or driving, showing movement in real time.",
    "memoryJournalTitle": "Memory Journal",
    "memoryJournalBody": "Users can save private personal memories, photos, and videos connected to heritage places.",
    "heritageVideos": "Heritage Videos",
    "liveGeolocation": "Geolocalización en vivo",
    "failedLocation": "Failed to get location",
    "startingLocation": "Starting live location tracking...",
    "mapReady": "Live movement map is ready.",
    "mapInstruction": "The blue navigation marker follows your phone GPS while walking or driving. The story is generated by Gemini API when a nearby place is detected.",
    "refreshLocation": "Regenerate / Refresh Location",
    "nearest": "Nearest",
    "kmAway": "km away",
    "generatingStory": "Generating AI Heritage Story",
    "generatingStoryBody": "HeritageBot is generating a context-aware story using Gemini API...",
    "contextStoryTitle": "AI Context-Aware Heritage Story",
    "generatingImage": "Generating AI Heritage Image",
    "generatingImageBody": "HeritageBot is creating an AI image based on your nearby location and generated story...",
    "aiImageTitle": "AI Location-Based Heritage Image",
    "aiImageFallbackTitle": "Heritage Image Preview",
    "aiImageFallbackBody": "The live AI image service is unavailable, so HeritageBot is showing a local illustrative heritage preview for this place.",
    "noVideo": "No Video Available",
    "noVideoBody": "This nearest place has no assigned video yet.",
    "addMemoryHere": "Add Personal Memory Here",
    "noSavedMemories": "No saved memories for this place yet.",
    "previousMemories": "Your Previous Memories Here",
    "chooseHeritagePlace": "Choose Heritage Place",
    "chooseHeritagePlaceBody": "Select where this journal memory belongs.",
    "noJournal": "No journal yet. Tap + to add a letter, photos, or videos connected to a heritage place.",
    "addMemory": "Add Memory",
    "addMemorySubtitle": "Write a letter or add family photos/videos connected to this place.",
    "writeMemoryLetter": "Write your memory letter",
    "selectedPictures": "Selected Pictures",
    "selectedVideos": "Selected Videos",
    "saveMemory": "Save Memory",
    "saving": "Saving...",
    "journalSaved": "Journal memory saved.",
    "profileUser": "HeritageBot User",
    "noEmail": "No email available",
    "changePassword": "Cambiar contraseña",
    "changePasswordUnavailable": "Change Password Unavailable",
    "changePasswordUnavailableMsg": "Change password is only available for email/password accounts.",
    "logout": "Cerrar sesión",
    "systemNote": "System Note",
    "systemNoteBody": "This profile is connected to Firebase Authentication. Email, Gmail, and Facebook users will appear in Firebase Authentication → Users.",
    "languageSettings": "Configuración de idioma",
    "languageSaved": "Preferencia de idioma guardada.",
    "attachedVideo": "Attached video"
  }
};


