// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFfx4YpiBZXlytKpPHZzXPdh91Izvx4TQ',
    appId: '1:879489283255:web:d549274de80741e67e0932',
    messagingSenderId: '879489283255',
    projectId: 'heritagebot-bdc39',
    authDomain: 'heritagebot-bdc39.firebaseapp.com',
    storageBucket: 'heritagebot-bdc39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRLCDJDb8mdSPZRGUcf5r2EFCtWxfzNq0',
    appId: '1:879489283255:android:a7fd65b0a61a839e7e0932',
    messagingSenderId: '879489283255',
    projectId: 'heritagebot-bdc39',
    storageBucket: 'heritagebot-bdc39.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvK0VdQ9WfhYVezb2jVyJXzYQ79oH-zp4',
    appId: '1:879489283255:ios:b5784b67aff0291f7e0932',
    messagingSenderId: '879489283255',
    projectId: 'heritagebot-bdc39',
    storageBucket: 'heritagebot-bdc39.firebasestorage.app',
    androidClientId: '879489283255-duolubnrg09ntivv9k0vkidqn2n16id6.apps.googleusercontent.com',
    iosClientId: '879489283255-tank7ktbnnr8v4su6jpj5dhsd0u3k6vs.apps.googleusercontent.com',
    iosBundleId: 'com.example.heritagebot',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvK0VdQ9WfhYVezb2jVyJXzYQ79oH-zp4',
    appId: '1:879489283255:ios:b5784b67aff0291f7e0932',
    messagingSenderId: '879489283255',
    projectId: 'heritagebot-bdc39',
    storageBucket: 'heritagebot-bdc39.firebasestorage.app',
    androidClientId: '879489283255-duolubnrg09ntivv9k0vkidqn2n16id6.apps.googleusercontent.com',
    iosClientId: '879489283255-tank7ktbnnr8v4su6jpj5dhsd0u3k6vs.apps.googleusercontent.com',
    iosBundleId: 'com.example.heritagebot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFfx4YpiBZXlytKpPHZzXPdh91Izvx4TQ',
    appId: '1:879489283255:web:28a70b6e68bfc0697e0932',
    messagingSenderId: '879489283255',
    projectId: 'heritagebot-bdc39',
    authDomain: 'heritagebot-bdc39.firebaseapp.com',
    storageBucket: 'heritagebot-bdc39.firebasestorage.app',
  );
}
